name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone ioquake3
      shell: cmd
      run: |
        git clone https://github.com/ioquake/ioq3.git ../ioq3
    - name: Run premake
      shell: powershell
      run: |
        .\premake5.exe vs2019
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Build
      shell: cmd
      run: |
        msbuild build\vs2019\ioquake3.sln /p:Configuration=Release /p:Platform="Win32" /verbosity:minimal
